engines:
  shellcheck:
    enabled: true
    checks:
      SC2039:
        enabled: false
  # markdownlint:
  #   enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
    exclude_fingerprints:
    - 1365834d5e34d87fd4ff8ea7c3c25d3e
  rubocop:
    enabled: true

ratings:
  paths:
  - Gemfile.lock
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.module"
  - "**.py"
  - "**.rb"
  - "**.sass"
  - "**.scss"
  - "**.md"

exclude_paths:
- node_modules/
- lib/
- assets/
- images/
