DirectoryPath: _site
CheckDoctype: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreURLs:
- "history.newtheatre.org.uk"
- "photos.smugmug.com"
- "photos.newtheatre.org.uk"
- "archive.is"
IgnoreDirs:
- "^lib"

